package net.skeletonjack.projectEuler

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting
 * with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
 * the sum of the even-valued terms.
 */
object Two {

  def generateFibonacciTerms(stopCollectingAt: Int, filter: Int => Boolean = _ => true): List[Int] = {

    def accumulateFibonacciTerms(currentTerm: Int, previousTerm: Int, collectedTerms: List[Int]): List[Int] = {
      val newTerm = currentTerm + previousTerm

      if (newTerm >= stopCollectingAt)
        collectedTerms
      else
        accumulateFibonacciTerms(newTerm, currentTerm, if (filter(newTerm))
                                                         collectedTerms :+ newTerm
                                                       else
                                                         collectedTerms
        )

    }

    accumulateFibonacciTerms(1, 0, List())
  }

  def main(args: Array[String]) {
    val evenFibTerms = generateFibonacciTerms(4000000, _ % 2 == 0)
    val totalOfEvenFibTerms = evenFibTerms.sum

    println(s"The total of all, even Fibonacci terms less than 4,000,000 is $totalOfEvenFibTerms.")
  }

}
